In [1]:
import pandas as pd
import numpy as np

In [2]:
cols = ['Transaction unique identifier',
'Price',
'Date of Transfer',
'Postcode',
'Property Type',
'Old_New'
'Duration',
'PAON',
'SAON',
'Street', 
'Locality', 
'Town_City',
'District',
'County',
'PPD Category Type',
'Record Status - monthly file only']

In [3]:
dta = pd.read_csv('Documents/pp-2018-part1.csv', index_col= False,header=None, names=cols)

In [4]:
dta.head()

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old_NewDuration,PAON,SAON,Street,Locality,Town_City,District,County,PPD Category Type,Record Status - monthly file only
0,{7E86B6FA-70B7-458C-E053-6B04A8C0C84C},435000,2018-06-22 00:00,UB10 8FQ,F,Y,L,HINDS COURT,FLAT 19,PERKINS GARDENS,ICKENHAM,UXBRIDGE,HILLINGDON,GREATER LONDON,A
1,{7E86B6FA-70B8-458C-E053-6B04A8C0C84C},355000,2018-10-19 00:00,UB3 1DZ,F,Y,L,"BOILER HOUSE, 2",FLAT 54,MATERIAL WALK,NaN,HAYES,HILLINGDON,GREATER LONDON,A
2,{7E86B6FA-70B9-458C-E053-6B04A8C0C84C},465000,2018-09-14 00:00,EN5 2FQ,F,Y,L,"DELPHI HOUSE, 4",FLAT 5,HERA AVENUE,NaN,BARNET,BARNET,GREATER LONDON,A
3,{7E86B6FA-70BA-458C-E053-6B04A8C0C84C},540000,2018-09-14 00:00,EN5 2FQ,F,Y,L,"DELPHI HOUSE, 4",FLAT 17,HERA AVENUE,NaN,BARNET,BARNET,GREATER LONDON,A
4,{7E86B6FA-70BB-458C-E053-6B04A8C0C84C},415000,2018-10-02 00:00,N13 5EX,F,Y,L,"HAZELTREE LODGE, 16 - 18",FLAT 9,HAZELWOOD LANE,NaN,LONDON,ENFIELD,GREATER LONDON,A

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
dta= pd.concat([dta,pd.get_dummies(dta['Property Type'])], axis=0)

/Users/craigledgerwood/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [14]:
dta.head()

,County,D,Date of Transfer,District,F,Locality,O,Old_NewDuration,PAON,PPD Category Type,Postcode,Price,Property Type,Record Status - monthly file only,S,SAON,Street,T,Town_City,Transaction unique identifier
0,HILLINGDON,NaN,2018-06-22 00:00,UXBRIDGE,NaN,PERKINS GARDENS,NaN,Y,L,GREATER LONDON,UB10 8FQ,435000.0,F,A,NaN,HINDS COURT,FLAT 19,NaN,ICKENHAM,{7E86B6FA-70B7-458C-E053-6B04A8C0C84C}
1,HILLINGDON,NaN,2018-10-19 00:00,HAYES,NaN,MATERIAL WALK,NaN,Y,L,GREATER LONDON,UB3 1DZ,355000.0,F,A,NaN,"BOILER HOUSE, 2",FLAT 54,NaN,NaN,{7E86B6FA-70B8-458C-E053-6B04A8C0C84C}
2,BARNET,NaN,2018-09-14 00:00,BARNET,NaN,HERA AVENUE,NaN,Y,L,GREATER LONDON,EN5 2FQ,465000.0,F,A,NaN,"DELPHI HOUSE, 4",FLAT 5,NaN,NaN,{7E86B6FA-70B9-458C-E053-6B04A8C0C84C}
3,BARNET,NaN,2018-09-14 00:00,BARNET,NaN,HERA AVENUE,NaN,Y,L,GREATER LONDON,EN5 2FQ,540000.0,F,A,NaN,"DELPHI HOUSE, 4",FLAT 17,NaN,NaN,{7E86B6FA-70BA-458C-E053-6B04A8C0C84C}
4,ENFIELD,NaN,2018-10-02 00:00,LONDON,NaN,HAZELWOOD LANE,NaN,Y,L,GREATER LONDON,N13 5EX,415000.0,F,A,NaN,"HAZELTREE LODGE, 16 - 18",FLAT 9,NaN,NaN,{7E86B6FA-70BB-458C-E053-6B04A8C0C84C}

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [20]:
X = dta[['F','S','T','D','O']].fillna(0).values
y = dta['Price'].values

In [21]:
X_train, y_train, x_test, y_test = train_test_split(X,y, test_size=0.3, random_state=5)

In [22]:
lr = LogisticRegression()

In [25]:
X_train.shape

(707989, 5)

In [23]:
lr.fit(X_train, y_train)

/Users/craigledgerwood/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: bad input shape (303425, 5)

In [28]:
dta['Property Type']

0         F
1         F
2         F
3         F
4         F
5         F
6         F
7         F
8         F
9         F
10        F
11        F
12        F
13        F
14        F
15        F
16        T
17        F
18        T
19        F
20        F
21        F
22        F
23        D
24        F
25        F
26        F
27        F
28        F
29        T
         ..
505677    T
505678    T
505679    S
505680    D
505681    S
505682    T
505683    S
505684    S
505685    F
505686    D
505687    S
505688    T
505689    D
505690    S
505691    T
505692    F
505693    S
505694    T
505695    D
505696    D
505697    D
505698    F
505699    F
505700    F
505701    D
505702    F
505703    S
505704    D
505705    T
505706    S
Name: Property Type, Length: 505707, dtype: object